import { Product } from "@/types/product";

// Demo products for development — replace with Firestore data in production
export const DEMO_PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Classic Cotton T-Shirt",
    slug: "classic-cotton-tshirt",
    description:
      "Premium 100% cotton t-shirt with a relaxed fit. Perfect for everyday wear.",
    price: 799,
    salePrice: 499,
    category: "fashion",
    images: [],
    variants: [
      { size: "S", color: "White", stock: 20 },
      { size: "M", color: "White", stock: 15 },
      { size: "L", color: "Black", stock: 10 },
    ],
    stock: 45,
    featured: true,
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Wireless Bluetooth Earbuds",
    slug: "wireless-bluetooth-earbuds",
    description:
      "Premium sound quality with active noise cancellation. 24hr battery life.",
    price: 2999,
    salePrice: 1999,
    category: "electronics",
    images: [],
    variants: [],
    stock: 30,
    featured: true,
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Minimalist Desk Lamp",
    slug: "minimalist-desk-lamp",
    description:
      "Modern LED desk lamp with touch dimmer and USB charging port.",
    price: 1499,
    salePrice: null,
    category: "home-living",
    images: [],
    variants: [
      { size: "Standard", color: "Black", stock: 12 },
      { size: "Standard", color: "White", stock: 8 },
    ],
    stock: 20,
    featured: true,
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Leather Crossbody Bag",
    slug: "leather-crossbody-bag",
    description:
      "Genuine leather crossbody bag with adjustable strap and multiple compartments.",
    price: 3499,
    salePrice: 2799,
    category: "accessories",
    images: [],
    variants: [
      { size: "One Size", color: "Tan", stock: 5 },
      { size: "One Size", color: "Black", stock: 7 },
    ],
    stock: 12,
    featured: true,
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "5",
    name: "Organic Scented Candle Set",
    slug: "organic-scented-candle-set",
    description:
      "Set of 3 hand-poured soy candles in lavender, vanilla, and sandalwood.",
    price: 999,
    salePrice: 749,
    category: "home-living",
    images: [],
    variants: [],
    stock: 50,
    featured: false,
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "6",
    name: "Smartwatch Pro X",
    slug: "smartwatch-pro-x",
    description:
      "Fitness tracking, heart rate monitor, GPS, and 7-day battery life.",
    price: 5999,
    salePrice: 4499,
    category: "electronics",
    images: [],
    variants: [
      { size: "42mm", color: "Black", stock: 10 },
      { size: "44mm", color: "Silver", stock: 8 },
    ],
    stock: 18,
    featured: true,
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "7",
    name: "Printed Silk Scarf",
    slug: "printed-silk-scarf",
    description:
      "Luxurious 100% silk scarf with hand-painted floral print.",
    price: 1299,
    salePrice: null,
    category: "fashion",
    images: [],
    variants: [
      { size: "Standard", color: "Blue", stock: 15 },
      { size: "Standard", color: "Rose", stock: 12 },
    ],
    stock: 27,
    featured: false,
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "8",
    name: "Stainless Steel Water Bottle",
    slug: "stainless-steel-water-bottle",
    description:
      "Double-wall insulated bottle. Keeps drinks cold 24hrs / hot 12hrs.",
    price: 699,
    salePrice: 499,
    category: "accessories",
    images: [],
    variants: [
      { size: "500ml", color: "Matte Black", stock: 30 },
      { size: "750ml", color: "Matte Black", stock: 20 },
    ],
    stock: 50,
    featured: true,
    active: true,
    createdAt: new Date().toISOString(),
  },
];
